### ISSUE TITLE
Core Version Number

### ISSUE THREAD

**Issue by RetroDriven** [joshcampbell191/openfpga-cores-inventory#8]
Would it be possible to add the Core Version Numbers into the API? I want to build some auto notifications into Discord for when a new Core drops or gets updated.

**Comment by goronfreeman** [comment]
Unfortunately, since we're using GitHub Pages as a host for the API right now, we can only serve up static content. Adding version numbers would mean having to manually update the YAML file every time a new version was released. If this gets traction, it might be worth separating the API out to another project so we can have some dynamic content.

Unfortunately the Heroku free tier is going away, or else I would spin something up quick.

**Comment by joshcampbell191** [comment]
As @goronfreeman said, they would have to be manually tracked and updated in the YML. Alternatively, you can register to the ATOM feeds for the corresponding repositories to receive notifications for updates.

**Comment by goronfreeman** [comment]
Good news. I started working on a PR (#16) to parse out more information from the cores' JSON files. This will include the version number.

**Comment by goronfreeman** [comment]
@RetroDriven this is now available in API v1

**Comment by RetroDriven** [comment]
Oh very nice thank you 😊

**Comment by joshcampbell191** [comment]
@RetroDriven it's also available in v0 however, please note that only the latest release (or pre-release) for each core is listed.
